-- -- Add course_id column to articles table
-- ALTER TABLE articles ADD course_id BIGINT;
--
-- -- Add foreign key constraint for course_id referencing courses table
-- ALTER TABLE articles
--     ADD CONSTRAINT fk_course
--         FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE;

-- Insert Articles for Physics 101 (course_id = 1)
INSERT INTO articles (title, content, subject_area, course_id)
VALUES
    ('Introduction to Newtonian Physics',
     'Newtonian mechanics is the branch of classical mechanics that focuses on the motion of objects and how they are affected by various forces. The fundamental principles of this branch are derived from the laws of motion established by Sir Isaac Newton. These laws describe how the velocity of an object changes when it is subjected to external forces. \
      The first law, often referred to as the law of inertia, states that an object will remain at rest or in uniform motion in a straight line unless acted upon by a net external force. The second law provides a quantitative description of the force needed to alter the motion of an object, expressed as the product of the object’s mass and acceleration (F = ma). The third law of motion states that for every action, there is an equal and opposite reaction. These laws have profound implications in understanding everything from the motion of everyday objects to the dynamics of planetary bodies. \
      Newtonian mechanics also introduces concepts such as inertia, mass, force, and momentum. For example, inertia refers to the resistance of any physical object to a change in its state of motion. Mass is a measure of the amount of matter in an object, and force is any interaction that changes the motion of an object. Momentum, meanwhile, is the product of the mass and velocity of an object and is a key concept in understanding collisions and other physical interactions. The study of Newtonian mechanics forms the foundation of many other areas in physics, including engineering and astrophysics.',
     'Physics', 2),

    ('Thermodynamics Basics',
     'Thermodynamics is the branch of physics that deals with the relationships between heat, energy, and work. It is a vital area of study, especially in understanding the behavior of systems under different conditions of temperature and energy. The principles of thermodynamics are essential in fields ranging from physics and chemistry to engineering and environmental science. \
      There are four main laws of thermodynamics, starting with the zeroth law, which establishes the concept of temperature. It states that if two systems are each in thermal equilibrium with a third system, then they are in thermal equilibrium with each other. This law allows for the definition of temperature as a measurable quantity. \
      The first law of thermodynamics, also known as the law of energy conservation, states that energy cannot be created or destroyed, only transferred or changed in form. For example, in a closed system, the total energy remains constant, even though energy may be transferred from one part of the system to another. The second law of thermodynamics deals with entropy, a measure of disorder or randomness in a system. It states that in any natural thermodynamic process, the total entropy of a system and its surroundings will increase over time, approaching a maximum. This explains why some processes, such as the mixing of gases, are irreversible. \
      The third law of thermodynamics deals with absolute zero, the point at which a system’s entropy reaches its minimum possible value. At this temperature, theoretically, all molecular motion ceases. Understanding these laws provides a framework for analyzing energy transformations and predicting the behavior of physical systems.',
     'Physics', 2);

-- Insert Articles for Chemistry Basics (course_id = 2)
INSERT INTO articles (title, content, subject_area, course_id)
VALUES
    ('Introduction to Chemical Reactions',
     'A chemical reaction is a process in which substances, known as reactants, interact with one another to form new substances called products. These reactions involve the breaking and forming of chemical bonds, which are the forces holding atoms together in molecules. The study of chemical reactions is fundamental to understanding chemistry, and such reactions are the basis for a wide variety of processes in biology, industry, and everyday life. \
      There are several different types of chemical reactions, each of which involves different interactions between reactants. These include synthesis reactions, where multiple reactants combine to form a single product, and decomposition reactions, where a compound breaks down into two or more simpler substances. Other common types of reactions include single replacement reactions, double replacement reactions, and combustion reactions. \
      One of the most important factors that affect chemical reactions is energy. Reactions can either absorb energy (endothermic) or release energy (exothermic). In exothermic reactions, energy is released in the form of heat, light, or sound, which is why some reactions, such as combustion, are highly energetic. Endothermic reactions, on the other hand, require the input of energy to proceed. The rate of a chemical reaction can also be influenced by factors such as temperature, pressure, concentration of reactants, and the presence of catalysts. Catalysts are substances that speed up the rate of a reaction without being consumed in the process. \
      Chemical reactions are the foundation of many processes in the natural world, from the metabolism of food in living organisms to the synthesis of new materials in laboratories. Understanding these reactions allows scientists to predict the behavior of different substances and design processes that harness chemical change for practical purposes.',
     'Chemistry', 3),

    ('Organic Chemistry Primer',
     'Organic chemistry is the branch of chemistry that focuses on the structure, properties, composition, and reactions of carbon-containing compounds. These compounds, known as organic compounds, include not only hydrocarbons but also compounds containing other elements such as oxygen, nitrogen, sulfur, and halogens. Organic chemistry plays a central role in many industries, including pharmaceuticals, agriculture, and manufacturing, as well as in biological systems. \
      One of the key features of organic compounds is the ability of carbon atoms to form strong covalent bonds with other carbon atoms, allowing for the formation of long chains and complex ring structures. This ability gives rise to a vast array of different compounds, many of which form the basis of life on Earth. For example, organic compounds such as carbohydrates, proteins, lipids, and nucleic acids are essential components of living organisms. \
      Organic reactions typically involve the breaking and forming of covalent bonds. These reactions can be classified into several types, including addition reactions, substitution reactions, elimination reactions, and rearrangement reactions. The mechanisms of these reactions are central to understanding how different compounds behave and interact with one another. One of the challenges in organic chemistry is the ability to synthesize complex molecules from simpler ones, a process that requires precise control over reaction conditions and the use of catalysts to guide reactions toward the desired products. \
      Organic chemistry is a constantly evolving field, with new compounds and reactions being discovered regularly. Advances in this area have had a significant impact on fields such as medicine, where organic compounds are the basis for many drugs and therapies, and in materials science, where organic compounds are used to create new polymers and materials with unique properties.',
     'Chemistry', 3);

-- Insert Articles for Intro to Computer Science (course_id = 3)
INSERT INTO articles (title, content, subject_area, course_id)
VALUES
    ('What is Programming?',
     'Programming is the process of designing and building an executable set of instructions that a computer can follow to perform a task. These instructions are written in programming languages, which are formal languages that define the syntax and semantics of the commands to be executed. The most popular programming languages include Python, Java, C++, and JavaScript, each of which has its own strengths and is suited to different kinds of tasks. \
      The first step in programming is defining the problem to be solved and planning a solution, usually in the form of an algorithm. An algorithm is a step-by-step procedure for performing a task or solving a problem, and it can be implemented in any programming language. Once the algorithm is defined, the next step is to write the program code. This involves using the appropriate syntax of the chosen programming language to write commands that the computer can interpret and execute. \
      Programs can be written for a wide variety of tasks, from simple operations like adding two numbers to complex systems that control the functioning of an entire organization. In addition to writing code, programmers also need to test their programs to ensure that they work correctly. This involves identifying and fixing errors, or bugs, that may be present in the code. Debugging is an essential part of the programming process, and it requires both technical knowledge and problem-solving skills. \
      Programming is a critical skill in today’s digital world, with applications in fields ranging from business and engineering to entertainment and scientific research. As technology continues to advance, the demand for skilled programmers is expected to grow, making programming a valuable and highly sought-after skill.',
     'Computer Science', 4),

    ('Understanding Data Structures',
     'Data structures are ways of organizing and storing data so that it can be accessed and modified efficiently. The choice of data structure depends on the type of operations that need to be performed and the efficiency requirements of those operations. Some of the most commonly used data structures include arrays, linked lists, stacks, queues, and trees. Each of these structures has its own strengths and weaknesses and is suited to different types of tasks. \
      Arrays are one of the simplest data structures and consist of a fixed-size sequence of elements, all of which are of the same type. Arrays are efficient for accessing elements by their index, but they are less efficient for operations such as insertion and deletion, which may require shifting elements. Linked lists, on the other hand, consist of nodes that are linked together, with each node containing a reference to the next node in the sequence. This allows for efficient insertion and deletion, but accessing elements in a linked list can be slower than in an array. \
      Stacks and queues are abstract data structures that follow specific rules for how data can be added or removed. A stack is a Last-In-First-Out (LIFO) structure, meaning that the last element added is the first to be removed. A queue is a First-In-First-Out (FIFO) structure, meaning that the first element added is the first to be removed. Both stacks and queues are useful for managing tasks that need to be processed in a particular order, such as function calls or waiting lines. \
      Trees are hierarchical data structures that consist of nodes connected by edges. Each node has a parent node and zero or more child nodes. Trees are used in a variety of applications, including representing hierarchical relationships, searching, and sorting. One common type of tree is the binary search tree, where each node has at most two children and the left child is less than the parent while the right child is greater than the parent. Understanding data structures is crucial for writing efficient programs and solving complex problems in computer science.',
     'Computer Science', 4);